name = "nexusserverless"
compatibility_date = "2023-01-01"

kv_namespaces = [
    { binding = "TOKENS", id = "88fe9ca56e5249c5867c0415bc240e04", preview_id = "1727b3cdbeff4bd594fbe3b714bb21ac" },
    { binding = "CACHE", id = "8108546931274e6584686fee4e7e041d", preview_id = "d12db8ece300466aa7070a38ad0af33b" }
]

[[r2_buckets]]
binding = 'NXBUCKET' # <~ valid JavaScript variable name
bucket_name = 'nexusserverless'
preview_bucket_name = 'nexusserverlesspreview'